import Head from 'next/head'
import styled from 'styled-components';


 const Home = () => {
  return (
    <Wrapper>
      <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
        <Details>
          <h2 className="Home">Hello</h2>
          <p className="text-gray-500 font-normal mt-1">
             This works!!
          </p>
        </Details>
        
    </Wrapper>
  );
};


const Wrapper = styled.div`
  position: relative;
  background-color: ${props => props.theme.colors.blue200};
  height: 100vh;
`;

const Details = styled.div`
  flex: 1;

  @media (max-width: 768px) {
    display: flex;
    flex-direction: column-reverse;
  }
`;

export default Home